#! /bin/sh
$HOME/.config/polybar/launch.sh
feh --bg-scale --no-xinerama ~/backgrounds/solarized.png 

bspc monitor HDMI-0 -d 1 2 3 4 5 6
bspc monitor DP-4 -d 7 8 9 10 11 12
bspc config border_width         2
bspc config window_gap          19

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a peek state=floating
bspc rule -a zoom state=floating
bspc rule -a feh state=floating
bspc rule -a Gimp state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
